version: '2.4'
services:
  memory-leak:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:14.1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data